### ISSUE TITLE
Hello Aex12

### ISSUE THREAD

**Issue by otsaki** [Aex12/node-coinmarketcap#2]
I am trying to used your stuff for 0.10.48 nvm node.. can you help me? I can't get it working, maybe you can make support for it?

Peace!

**Comment by danieldunderfelt** [comment]
0.10 is seriously old, there is no reason to have backwards compatibility that far. Use NVM to upgrade!

**Comment by Aex12** [comment]
I agree with Daniel. I don't have any plans to add support for old nodejs versions.
